### PR TITLE
Issue #657: Fix encoding issues

### LINKED ISSUE #657: UTF-8 characters getting problems
Thank you for this library, I am using it for years, I was using up to version 3.1.0 but now I wanted to upgrade to 4.5 ang get problems with UTF-8 characters.

 - PHP IMAP version: tested anything newver than 3.1.0
 - PHP Version: 7.4
 - Type of execution: web server

Email with UTF-8 characters - these characters are unreadable.

The used code:
```php
	$mailbox = new PhpImap\Mailbox('{xxxxxx:143/imap4/notls/novalidate-cert}INBOX', 'xxxxx', 'xxxx');
	var_dump($mailbox->getServerEncoding()); //---GETTING UTF-8---
	$mailsIds = $mailbox->searchMailbox('ALL');
	if(!$mailsIds) return 0;
	foreach ($mailsIds as $key=>$mailsId)
	{
		$mail = $mailbox->getMail($mailsId);
		//var_dump($mail);
		
		var_dump($mail->textHtml);
	}
```

I tried to test any version newer than 3.1.0 but without success, only till 3.1.0 works.

Thank you.

### PR DESCRIPTION
**Pull request by Sebi94nbg**
Resolves #657.

### CODE REVIEW

File: src/PhpImap/DataPartInfo.php [hunk 1]
```diff
@@ -114,6 +114,12 @@ protected function convertEncodingAfterFetch(): string
             $this->data = $this->mail->decodeMimeStr(
                 (string) $this->data // Data to convert
             );
+
+            $this->data = $this->mail->convertToUtf8(
+                $this->data,
+                $this->charset
+            );
+            $this->charset = 'utf-8';
```
Comment (Sebi94nbg) [inline src/PhpImap/DataPartInfo.php:122]: Not sure, if we really need this line and if it makes sense to set it hard-coded here to UTF-8. Needs to be double-checked.

Comment (Sebi94nbg) [reply src/PhpImap/DataPartInfo.php]: Looks like as this isn't required. It also doesn't make any sense to always set it to UTF-8 AFTER converting the data as it maybe were before something else.
